# CI Name
name: 'Deployment Market Post'

# Only running when
on:
  push:
    branches:
      - main

jobs:
  build:
    # Running on latest version of Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node for Installing Dependencies
      - name: Setup Node Js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-lates: true

      - name: 'Installing Dependencies'
        run: yarn

      - name: 'Building Project'
        run: yarn build
